name: Build and test

# Run this workflow for all other branches than the production branch.
on:
  push:
    branches-ignore:
      - production-site

jobs:
  build-and-test-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: |
            infra/package-lock.json

      - name: Install infra dependencies
        run: npm ci

      - name: Lint
        run: npx eslint .

      - name: Code style
        run: npx prettier --check .

      - name: Test infra
        run: npm run test

  build-and-test-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: website

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
          cache-dependency-path: |
            website/package-lock.json

      - name: Install website dependencies
        run: npm ci

      - name: Build site
        run: npm run build
