name: Create production update PR

on:
  workflow_dispatch:

jobs:
  create-prod-update-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Production update PR
        run: |
          gh pr create --title 'Production update' --body 'Update production branch' --base production-site --head main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
