name: Create production update PR

on:
  workflow_dispatch:

jobs:
  create-prod-update-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Production update PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Production update'
          base: 'production-site'
          branch: 'main'
          delete-branch: false
          title: 'Production update'
          body: |
            Description here
          draft: false
